# --- CONFIGURACIÓN DE LA BASE DE DATOS MYSQL ---

# 1. Dónde está la base de datos.
# 'localhost' es tu ordenador. '3306' es el puerto estándar de MySQL.
# 'poketactics' es el nombre del esquema que acabas de crear.
# '?serverTimezone=UTC' evita problemas con la hora entre Java y MySQL.
spring.datasource.url=jdbc:mysql://localhost:3306/poketactics?serverTimezone=UTC

# 2. Tu usuario y contraseña de MySQL.
# Por defecto suele ser 'root', pero cámbialo si el tuyo es diferente.
spring.datasource.username=root
# ¡IMPORTANTE! Pon aquí tu contraseña real de MySQL.
spring.datasource.password=elpavoreal12150

# --- CONFIGURACIÓN DE JPA / HIBERNATE (La Magia) ---

# 3. Cómo debe comportarse Hibernate con las tablas.
# 'update': Si creas una clase Java nueva (una Entidad), Hibernate CREARÁ la tabla.
# Si cambias algo en la clase, Hibernate INTENTARÁ actualizar la tabla.
spring.jpa.hibernate.ddl-auto=update

# 4. Mostrar las consultas SQL en la consola.
# Muy útil para aprender: verás qué SQL escribe Hibernate por ti.
spring.jpa.show-sql=true

# 5. Formatear el SQL para que sea más fácil de leer.
spring.jpa.properties.hibernate.format_sql=true

# 6. Indicarle que estamos usando MySQL para que optimice las consultas.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect